### ISSUE TITLE
Setup connection: cannot resolve hostname

### ISSUE THREAD

**Issue by ronghongbo** [intel/vscode-oneapi-devcloud-connector#3]
Hello, I followed the instructions to install. Everything is fine until this step: "Press Ctrl+Shift+P ( or View -> Command Palette... ) to open the Command Palette. Type DevCloud and select Intel DevCloud: Setup connection". In this step, first there is such a window:
![image](https://user-images.githubusercontent.com/9489325/154203822-df4bf6aa-08f8-43f6-9324-7a56e5eb05c8.png)

And then:
![image](https://user-images.githubusercontent.com/9489325/154203892-dc8021db-e0b1-4396-ae0e-5c5429bbbcc7.png)

Please take a look. 
Thanks!
Hongbo

**Comment by vsorokin11** [comment]
Hello @ronghongbo 

This node can be faulty. Could you please another node device in the extension settings (for example, "xeon" or "quad_gpu") and try to connect again?

**Comment by ronghongbo** [comment]
Thanks for the reply, Vladimir. I tried several others (core s011-n004, Xeon s001-n020, and quad-gpu 012-n003), and all of them failed for the same errors. It seems to me that "cannot resolve hostname ....aidevcloud" is the real issue. Maybe some setting issue on my side.

**Comment by ronghongbo** [comment]
C:/cygwin/home/hrong1/config:
Host devcloud
#replace with your own user name
User u89062
IdentityFile ~/.ssh/devcloud-access-key-89062.txt
ProxyCommand ssh -T -i ~/.ssh/devcloud-access-key-89062.txt ***@***.******@***.***>

**Comment by ronghongbo** [comment]
Sorry, the previous message was unclean. Just update it.

**Comment by vsorokin11** [comment]
I need full config file. You showed only part of config.

**Comment by vsorokin11** [comment]
The config file must be as below:

Host devcloud
User u89062
IdentityFile ~/.ssh/devcloud-access-key-u89062.txt
ProxyCommand ssh -T -i ~/.ssh/devcloud-access-key-u89062.txt guest@ssh.devcloud.intel.com

Host devcloud.proxy
User u89062
Port 4022
IdentityFile ~/.ssh/devcloud-access-key-u89062.txt
ProxyCommand ssh -T devcloud-via-proxy

# If you must route outgoing SSH connection via a corporate proxy,
# replace PROXY_HOSTNAME and PORT below with the values provided by
# your network administrator.
Host devcloud-via-proxy
User guest
Hostname ssh.devcloud.intel.com
IdentityFile ~/.ssh/devcloud-access-key-u89062.txt
LocalForward 4022 c009:22
ProxyCommand nc -x PROXY_HOSTNAME:PORT %h %p
################################################################################################

################################################################################################
# DevCloud VSCode config
################################################################################################
Host devcloud-vscode
UserKnownHostsFile /dev/null
StrictHostKeyChecking no
Hostname localhost
User u89062
Port 5022
IdentityFile ~/.ssh/devcloud-access-key-u89062.txt
################################################################################################

################################################################################################
# SSH Tunnel config
################################################################################################
Host *.aidevcloud
User u89062
IdentityFile ~/.ssh/devcloud-access-key-u89062.txt
ProxyCommand ssh -T devcloud nc %h %p
LocalForward 5022 localhost:22
LocalForward 5901 localhost:5901
################################################################################################

**Comment by ronghongbo** [comment]
Thanks a lot, Vladimir. It works now.

**Comment by ronghongbo** [comment]
Yes. Thank you, Vladimir!

**Comment by ronghongbo** [comment]
Hello Vladimir, the above config file has enabled me to ssh devcloud and use VSCode WITHOUT proxy. However, I encountered some issue when using proxy. First, I modified the line 
```
ProxyCommand nc -x PROXY_HOSTNAME:PORT %h %p
```
into
```
ProxyCommand nc -x proxy-us.intel.com:1080 %h %p
```
Then in a Cygwin64 terminal:
```
$ ssh devcloud.proxy 
u89062@login-2:~$  qsub -I -l nodes=s001-n078:ppn=2 
```
Both commands above succeed.

Then in another Cygwin64 terminal:
```
$ ssh s001-n078.aidevcloud
ssh: connect to host ssh.devcloud.intel.com port 22: Connection timed out
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```
Any idea? 

Thanks!
Hongbo

**Comment by ronghongbo** [comment]
This configuration works perfectly with proxy. Thanks, Vladimir!

Just a note: I found that with proxy and without proxy, two different configuration files should be used. So for a specific scenario, one of the two configurations you provided above should be copied to .ssh/config to make things work.

**Comment by amakarev** [comment]
@ronghongbo Hello! In the extension settings, you can specify whether you use a proxy or not. Depending on this setting, the extension should automatically modify your config file, so there is no need to keep two separate config files.
![image](https://user-images.githubusercontent.com/81574619/185116804-472707e5-4309-4eea-ab65-bed4b710ca49.png)

**Comment by ronghongbo** [comment]
Thanks, Alexey!

**Comment by ronghongbo** [comment]
Hello, I have not used VScode-devcloud for quite a while, and today encounters a new problem without changing any configuration:
In a Cygwin window:
   ssh devcloud
   qsub -I -l nodes=s001-n078:ppn=2
   Both commands succeed.
In another Cygwin window:
  $ ssh s001-n078.aidevcloud
nc: getaddrinfo: Name or service not known
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535 

Any idea? 
Thanks!
Hongbo

**Comment by ronghongbo** [comment]
Forget it. After restarting my local machine, all commands work again.
