### ISSUE TITLE
VSCode on Ubuntu fails to establish a SSH connection to DevCloud

### ISSUE THREAD

**Issue by irudkin** [intel/vscode-oneapi-devcloud-connector#8]
< Bumping up   @tingleby @vsorokin11 @amakarev @samples-ci @bdmoore1 >

I have just recently followed your instructions (this and Intel's Connect to DevCloud with Visual Studio Code documentation). Installed:

-     VS Code [SSH extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh)
-     VS Code [DevCloud Connector extension](https://marketplace.visualstudio.com/items?itemName=intel-corporation.vscode-oneapi-devcloud-connector)

Following the instructions to set up an ssh key to connect to the DevCloud and this works fine. I can ssh login and access my DevCloud home directory all using a terminal window.

However, when asking VSCode via Intel DevCloud extension to connect (Ctrl+shift+p Intel DevCloud Setup a connection), it hangs saying 'Connecting to head node... " for as the time out value, or immediately returns with Failed to create tunnel.... The timer has been set to 6 minutes. 

Incidently, using VSCode remote ssh does connect to the DevCloud letting me at my home directory. This appears to work ok.

Ultimately in the end, I would like to connect to a DevCloud node to build a DPC++ program using a VSCode project setup to use Microsoft C/C++ extension configuration tasks (Task.json, launch.json,..), then debug it using VScode, step into and over Kernel code.  I work for Codeplay and I am writing a series of technical articles on using VSCode to build and debug DPC++ programs.

The platform is Ubuntu 20.04.
Using VSCode 1.73.1
Tried with a background VPN off and on (remote working from home)
IT have confirmed I am not behind a SSH proxy.
See log text below.
Please advise as to the issue here and what needs to be done to resolve it. Thank you :-)

Session log:
###############################################################################
################################################################################
#
# Welcome to the Intel DevCloud for oneAPI Projects!
#
# 1) See https://devcloud.intel.com/oneapi/ for instructions and rules for
# the OneAPI Instance.
#
# 2) See https://github.com/intel/FPGA-Devcloud for instructions and rules for
# the FPGA Instance.
#
# Note: Your invitation email sent to you contains the authentication URL.
#
# If you have any questions regarding the cloud usage, post them at
# https://software.intel.com/en-us/forums/intel-devcloud
#
# Intel DevCloud Team
#
###############################################################################
#
# Note: Cryptocurrency mining on the Intel DevCloud is forbidden.
# Mining will lead to immediate termination of your account.
#
###############################################################################
Last login: Thu Dec  8 04:59:17 2022 from 10.9.0.249

u176998@login-2:~$

**Comment by amakarev** [comment]
@irudkin Hello. 
As I understand it, the problem is that the extension is not able to connect to DevCloud using the vscode extension and hangs at the step of connecting to the head node.
Could you try connecting using the latest version of the extension? (0.2.0)
https://marketplace.visualstudio.com/items?itemName=intel-corporation.vscode-oneapi-devcloud-connector

**Comment by irudkin** [comment]
@amakarev Hello and thank you for getting back to me. 
I have uninstalled the extension and reinstalled checking for 0.2.0. 
It does not connect. After  choosing a device, about  3 seconds it return with the error  'Failed to create tunnel....'
Rechecked settings:
* Public intel devcloud
* Connection timeout 300 seconds
* Cygwin not applicable
* Proxy not selected
* No proxy server
* Session timeout 06:00:00
VPN is off.

**Comment by amakarev** [comment]
@irudkin Is this reproducible on any specific device class like fpga or are you getting the same error with different devices?

**Comment by irudkin** [comment]
@amakarev It happens on any device class any node type build.

**Comment by amakarev** [comment]
@irudkin for clarification, you are not under a proxy and proxy is unchecked in the extension settings? That being said, from the cygwin terminal you can execute "ssh devcloud" and the connection succeeds?

**Comment by irudkin** [comment]
@amakarev I am not using a proxy and it is unchecked. I am using ubuntu OS and when I ssh to the DevCloud either using the terminal command 'ssh DevCloud' or via VSCode ssh remote explorer pane --> REMOTE --> devcloud, the connect to devcloud home directory is a success. Ctrl+Shift+p Intel DevCloud Setup Connection is not successful, to a DevCloud node (tunnel failure).

**Comment by amakarev** [comment]
@irudkin Could you share your ssh config file? You can drop it directly into this thread, removing personal information from it (User and IdentityFile fields) or send it to me at alexey.makarevich@intel.com

**Comment by irudkin** [comment]
@amakarev I have sent you my ssh config file to your email address.

**Comment by amakarev** [comment]
Hello. Is this playable with the latest version of the extension?
